# Generated by Django 4.0 on 2022-08-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_messagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagemodel', to='social.threadmodel'),
        ),
    ]
